model_configs:
    use_vq: True
    vq_params:
        embedding_dim: 32
        n_embeddings: 4096
        beta: 0.25
        decay: 0.99
        eps: 0.00001
        kmean_init: True
        
    backbone_configs:
        in_dim: 1
        h_dim: 128
        n_res_layers: 2
        res_h_dim: 32

train_configs:
    pretrain: False
    partial_pretrain: False
    pretrain_model_path: ./model.pth
    
    init_batch: 50

    dataset: mnist

    optimizer: Adam
    weight_decay: 0.0001
    
    criterion: mse
    
    lr: 0.0003
    
    batch_size: 128
    
    num_workers: 4
    
    
    log_dir: /data3/zwh/VQ_Selection_Real_Data/logs_mnist/Mnist_ori
    save_dir: /data3/zwh/VQ_Selection_Real_Data/save_mnist/Mnist_ori/
    max_epoch: 100