model_configs:
    use_vq: True
    vq_params:
        embedding_dim: 64
        n_embeddings: 512
        beta: 0.25
        decay: 0.99
        eps: 0.00001
        kmean_init: True
        
    backbone_configs:
        in_dim: 3
        h_dim: 128
        n_res_layers: 2
        res_h_dim: 32

train_configs:
    pretrain: True
    pretrain_model_path: /data3/zwh/VQ_Selection_Real_Data/save_fine_tune/Cifar10_ae/model.pth
    
    dataset: cifar10

    optimizer: Adam
    weight_decay: 0.0001
    
    criterion: mse
    
    lr: 0.0003
    
    batch_size: 128
    
    num_workers: 4
    
    log_dir: /data3/zwh/VQ_Selection_Real_Data/logs_fine_tune/Cifar10_adam
    save_dir: /data3/zwh/VQ_Selection_Real_Data/save_fine_tune/Cifar10_adam/
    max_epoch: 300