model_configs:
    use_vq: True
    vq_params:
        embedding_dim: 64
        n_embeddings: 512
        beta: 0.25
        decay: 0.99
        eps: 0.00001
        kmean_init: False
        
    backbone_configs:
        in_dim: 3
        h_dim: 64
        n_res_layers: 2
        res_h_dim: 32
        cov_configs:
            kernel: [4, 4, 4, 4, 4, 3]
            stride: [2, 2, 2, 2, 2, 1]
            padding: [1, 1, 1, 1, 1, 1]
            res_kernel: 3
            res_stride: 1
            res_padding: 1
        
    projection_dim: 64


train_configs:
    pretrain: False
    pretrain_model_path: ./model.pth
    
    dataset: cifar10

    init_batch: 1
    init_size: 5120


    optimizer: Adam
    weight_decay: 0.0001
    
    criterion: mse
    
    lr: 0.0003
    
    batch_size: 128
    
    num_workers: 4
    
    
    log_dir: /data3/zwh/VQ_Selection_Real_Data/logs_tight_bottleneck_vq/Cifar10_vq_512_1_1_64
    save_dir: /data3/zwh/VQ_Selection_Real_Data/save_tight_bottleneck_vq/Cifar10_vq_512_1_1_64
    max_epoch: 300
