model_configs:
    use_vq: True
    vq_params:
        embedding_dim: 32
        n_embeddings: 16384
        beta: 0.25
        decay: 0.99
        eps: 0.00001
        kmean_init: True
        
    backbone_configs:
        in_dim: 3
        h_dim: 128
        n_res_layers: 2
        res_h_dim: 32

train_configs:
    pretrain: False
    pretrain_model_path: None
    
    init_batch: 20

    init_size: 163840

    dataset: cifar10

    optimizer: Adam
    weight_decay: 0.0001
    
    criterion: mse
    
    lr: 0.0003
    
    batch_size: 128
    
    num_workers: 4
    
    log_dir: /data3/zwh/VQ_Selection_Real_Data/logs_codes_fixed_ratio/Cifar10_ori_16384
    save_dir: /data3/zwh/VQ_Selection_Real_Data/save_codes_fixed_ratio/Cifar10_ori_16384/
    max_epoch: 300

# see if the init batch works

