model_configs:
    use_vq: True
    vq_params:
        embedding_dim: 256
        n_embeddings: 1024
        beta: 0.25
        decay: 0.99
        eps: 0.00001
        kmean_init: True
        
    backbone_configs:
        in_dim: 3
        h_dim: 256
        n_res_layers: 2
        res_h_dim: 32
        cov_configs:
            kernel: [4, 2, 1]
            stride: [2, 2, 1]
            padding: [1, 0, 0]
            res_kernel: 1
            res_stride: 1
            res_padding: 0
        
    projection_dim: 8


train_configs:
    pretrain: False
    pretrain_model_path: ./model.pth
    
    dataset: cifar10

    init_batch: 2
    init_size: 10240


    optimizer: Adam
    weight_decay: 0.0001
    
    criterion: mse
    
    lr: 0.0003
    
    batch_size: 128
    
    num_workers: 4
    
    
    log_dir: /data3/zwh/VQ_Selection_Real_Data/logs_change_receptive_field_1024_code/Cifar10_ori_1024_256_8_1_re_6
    save_dir: /data3/zwh/VQ_Selection_Real_Data/save_change_receptive_field_1024_code/Cifar10_ori_1024_256_8_1_re_6
    max_epoch: 300
